version: 2.1
executors:
  node_executor:
    docker:
      - image: circleci/node:12.16.1-browsers

commands:
  install_dependencies:
    description: 'Checkout, install and cache npm dependencies'
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm

jobs:
  semantic_release_pr:
    executor: node_executor
    steps:
      - install_dependencies
      - run:
          name: Create artifacts folder
          command: mkdir -p semantic-release
      - run:
          name: Semantic-release dry run
          command: unset CIRCLE_PR_NUMBER && unset CIRCLE_PULL_REQUEST && unset CI_PULL_REQUEST && npx semantic-release --dry-run --branch ${CIRCLE_BRANCH} 2>&1 | tee semantic-release/index.log
      - store_artifacts:
          path: semantic-release

  semantic_release_master:
    executor: node_executor
    steps:
      - install_dependencies
      - run:
          name: Create artifacts folder
          command: mkdir -p semantic-release
      - run:
          name: Release master
          command: npx semantic-release 2>&1 | tee semantic-release/index.log
      - store_artifacts:
          path: semantic-release

workflows:
  version: 2

  npm_release:
    jobs:
      - semantic_release_master:
          context: NPM
          filters:
            branches:
              only: master
      - semantic_release_pr:
          context: NPM
          filters:
            branches:
              only: /^(?!master$).*/
